version: '3'
services:
  frontend:
    image: oneplatform-frontend:latest
    hostname: oneplatform.cloud
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    restart: unless-stopped
    networks:
      - frontend-net

networks:
  frontend-net:
    external: true
