version: '3'
services:
  oneplatform-frontend:
    hostname: oneplatform.cloud
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:80"
    restart: unless-stopped
    networks:
      - frontend-net

networks:
  frontend-net:
    external: true
